### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by andrewwatson** [seehuhn/fortuna#2]
I wrote a simple problem, much in the same style as your example but when I call RadomData() I get this panic:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xa code=0x2 addr=0x0 pc=0x52bc8]

goroutine 16 [running]:
runtime.panic(0x1eece0, 0x33b658)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xc5
github.com/seehuhn/fortuna.(_Accumulator).tryReseeding(0x0, 0x0, 0x0, 0x0)
    /Users/andrew/Development/go/src/github.com/seehuhn/fortuna/accumulator.go:173 +0x5f8
github.com/seehuhn/fortuna.(_Accumulator).RandomData(0x0, 0x20, 0x0, 0x0, 0x0)
    /Users/andrew/Development/go/src/github.com/seehuhn/fortuna/accumulator.go:203 +0x40
main.randomBytes(0x20, 0x0, 0x0, 0x0, 0x0, 0x0)

**Comment by seehuhn** [comment]
I can't reproduce this and without further information, there is little which can be done.
